default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  reconnect: true

development:
  <<: *default
  database: python-tester-dev
  username: python-tester
  password: passwd

production:
  <<: *default
  database: python-tester-prod
  username: python-tester
  password: passwd
